version: '3.7'

# "컴퓨터들"
services:
  # 컴퓨터 이름
  my-database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  # 컴퓨터 이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker
